spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/cinema
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        generate-ddl: true
