POST http://localhost:8080/seance
Content-Type: application/json
Accept: application/json

{
  "seanceId": "123abc",
  "email": "a@p.pl"
}

###
POST http://localhost:8080/seance/reserve
Content-Type: application/json
Accept: application/json

{
  "seanceId": "123abc",
  "reservationNumber": "resNumber",
  "chosenSeats": [1, 2, 3]
}